package org.ko.prototype.data.master.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ko.prototype.data.master.domain.bean.Slider;
import org.ko.prototype.data.master.domain.bean.SliderExample;

public interface SliderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    long countByExample(SliderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByExample(SliderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insert(Slider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insertSelective(Slider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<Slider> selectByExampleWithRowbounds(SliderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<Slider> selectByExample(SliderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    Slider selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Slider record, @Param("example") SliderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExample(@Param("record") Slider record, @Param("example") SliderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKeySelective(Slider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_slider
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKey(Slider record);
}