package org.ko.prototype.data.bean.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class User extends AbstractDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.id
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.login_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.password
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.mobile
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.email
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.nick_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.full_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.gender
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Short gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.age
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.birthday
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.avatar
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.credit
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.balance
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.checkout_count
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Short checkoutCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.last_checkout_time
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Date lastCheckoutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.last_login_time
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.login_count
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Short loginCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.last_login_ip
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.delete_status
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Short deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.login_token
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String loginToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.login_token_refresh_time
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Date loginTokenRefreshTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.trace_code_i
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String traceCodeI;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.trace_code_u
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String traceCodeU;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.host_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String hostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.create_user_id
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.create_by
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.create_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.update_user_id
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Integer updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.update_by
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_user.update_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table art_user
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.id
     *
     * @return the value of art_user.id
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.id
     *
     * @param id the value for art_user.id
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.login_name
     *
     * @return the value of art_user.login_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.login_name
     *
     * @param loginName the value for art_user.login_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.password
     *
     * @return the value of art_user.password
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.password
     *
     * @param password the value for art_user.password
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.mobile
     *
     * @return the value of art_user.mobile
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.mobile
     *
     * @param mobile the value for art_user.mobile
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.email
     *
     * @return the value of art_user.email
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.email
     *
     * @param email the value for art_user.email
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.nick_name
     *
     * @return the value of art_user.nick_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.nick_name
     *
     * @param nickName the value for art_user.nick_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.full_name
     *
     * @return the value of art_user.full_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.full_name
     *
     * @param fullName the value for art_user.full_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.gender
     *
     * @return the value of art_user.gender
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.gender
     *
     * @param gender the value for art_user.gender
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.age
     *
     * @return the value of art_user.age
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.age
     *
     * @param age the value for art_user.age
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.birthday
     *
     * @return the value of art_user.birthday
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.birthday
     *
     * @param birthday the value for art_user.birthday
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.avatar
     *
     * @return the value of art_user.avatar
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.avatar
     *
     * @param avatar the value for art_user.avatar
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.credit
     *
     * @return the value of art_user.credit
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.credit
     *
     * @param credit the value for art_user.credit
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.balance
     *
     * @return the value of art_user.balance
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.balance
     *
     * @param balance the value for art_user.balance
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.checkout_count
     *
     * @return the value of art_user.checkout_count
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Short getCheckoutCount() {
        return checkoutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.checkout_count
     *
     * @param checkoutCount the value for art_user.checkout_count
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setCheckoutCount(Short checkoutCount) {
        this.checkoutCount = checkoutCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.last_checkout_time
     *
     * @return the value of art_user.last_checkout_time
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Date getLastCheckoutTime() {
        return lastCheckoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.last_checkout_time
     *
     * @param lastCheckoutTime the value for art_user.last_checkout_time
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setLastCheckoutTime(Date lastCheckoutTime) {
        this.lastCheckoutTime = lastCheckoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.last_login_time
     *
     * @return the value of art_user.last_login_time
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.last_login_time
     *
     * @param lastLoginTime the value for art_user.last_login_time
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.login_count
     *
     * @return the value of art_user.login_count
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Short getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.login_count
     *
     * @param loginCount the value for art_user.login_count
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setLoginCount(Short loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.last_login_ip
     *
     * @return the value of art_user.last_login_ip
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.last_login_ip
     *
     * @param lastLoginIp the value for art_user.last_login_ip
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.delete_status
     *
     * @return the value of art_user.delete_status
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Short getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.delete_status
     *
     * @param deleteStatus the value for art_user.delete_status
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setDeleteStatus(Short deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.login_token
     *
     * @return the value of art_user.login_token
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getLoginToken() {
        return loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.login_token
     *
     * @param loginToken the value for art_user.login_token
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setLoginToken(String loginToken) {
        this.loginToken = loginToken == null ? null : loginToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.login_token_refresh_time
     *
     * @return the value of art_user.login_token_refresh_time
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Date getLoginTokenRefreshTime() {
        return loginTokenRefreshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.login_token_refresh_time
     *
     * @param loginTokenRefreshTime the value for art_user.login_token_refresh_time
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setLoginTokenRefreshTime(Date loginTokenRefreshTime) {
        this.loginTokenRefreshTime = loginTokenRefreshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.trace_code_i
     *
     * @return the value of art_user.trace_code_i
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getTraceCodeI() {
        return traceCodeI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.trace_code_i
     *
     * @param traceCodeI the value for art_user.trace_code_i
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setTraceCodeI(String traceCodeI) {
        this.traceCodeI = traceCodeI == null ? null : traceCodeI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.trace_code_u
     *
     * @return the value of art_user.trace_code_u
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getTraceCodeU() {
        return traceCodeU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.trace_code_u
     *
     * @param traceCodeU the value for art_user.trace_code_u
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setTraceCodeU(String traceCodeU) {
        this.traceCodeU = traceCodeU == null ? null : traceCodeU.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.host_name
     *
     * @return the value of art_user.host_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.host_name
     *
     * @param hostName the value for art_user.host_name
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.create_user_id
     *
     * @return the value of art_user.create_user_id
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.create_user_id
     *
     * @param createUserId the value for art_user.create_user_id
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.create_by
     *
     * @return the value of art_user.create_by
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.create_by
     *
     * @param createBy the value for art_user.create_by
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.create_date
     *
     * @return the value of art_user.create_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.create_date
     *
     * @param createDate the value for art_user.create_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.update_user_id
     *
     * @return the value of art_user.update_user_id
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.update_user_id
     *
     * @param updateUserId the value for art_user.update_user_id
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.update_by
     *
     * @return the value of art_user.update_by
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.update_by
     *
     * @param updateBy the value for art_user.update_by
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_user.update_date
     *
     * @return the value of art_user.update_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_user.update_date
     *
     * @param updateDate the value for art_user.update_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginName=").append(loginName);
        sb.append(", password=").append(password);
        sb.append(", mobile=").append(mobile);
        sb.append(", email=").append(email);
        sb.append(", nickName=").append(nickName);
        sb.append(", fullName=").append(fullName);
        sb.append(", gender=").append(gender);
        sb.append(", age=").append(age);
        sb.append(", birthday=").append(birthday);
        sb.append(", avatar=").append(avatar);
        sb.append(", credit=").append(credit);
        sb.append(", balance=").append(balance);
        sb.append(", checkoutCount=").append(checkoutCount);
        sb.append(", lastCheckoutTime=").append(lastCheckoutTime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", loginCount=").append(loginCount);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", loginToken=").append(loginToken);
        sb.append(", loginTokenRefreshTime=").append(loginTokenRefreshTime);
        sb.append(", traceCodeI=").append(traceCodeI);
        sb.append(", traceCodeU=").append(traceCodeU);
        sb.append(", hostName=").append(hostName);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateUserId=").append(updateUserId);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getNickName() == null ? other.getNickName() == null : this.getNickName().equals(other.getNickName()))
            && (this.getFullName() == null ? other.getFullName() == null : this.getFullName().equals(other.getFullName()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getAvatar() == null ? other.getAvatar() == null : this.getAvatar().equals(other.getAvatar()))
            && (this.getCredit() == null ? other.getCredit() == null : this.getCredit().equals(other.getCredit()))
            && (this.getBalance() == null ? other.getBalance() == null : this.getBalance().equals(other.getBalance()))
            && (this.getCheckoutCount() == null ? other.getCheckoutCount() == null : this.getCheckoutCount().equals(other.getCheckoutCount()))
            && (this.getLastCheckoutTime() == null ? other.getLastCheckoutTime() == null : this.getLastCheckoutTime().equals(other.getLastCheckoutTime()))
            && (this.getLastLoginTime() == null ? other.getLastLoginTime() == null : this.getLastLoginTime().equals(other.getLastLoginTime()))
            && (this.getLoginCount() == null ? other.getLoginCount() == null : this.getLoginCount().equals(other.getLoginCount()))
            && (this.getLastLoginIp() == null ? other.getLastLoginIp() == null : this.getLastLoginIp().equals(other.getLastLoginIp()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getLoginToken() == null ? other.getLoginToken() == null : this.getLoginToken().equals(other.getLoginToken()))
            && (this.getLoginTokenRefreshTime() == null ? other.getLoginTokenRefreshTime() == null : this.getLoginTokenRefreshTime().equals(other.getLoginTokenRefreshTime()))
            && (this.getTraceCodeI() == null ? other.getTraceCodeI() == null : this.getTraceCodeI().equals(other.getTraceCodeI()))
            && (this.getTraceCodeU() == null ? other.getTraceCodeU() == null : this.getTraceCodeU().equals(other.getTraceCodeU()))
            && (this.getHostName() == null ? other.getHostName() == null : this.getHostName().equals(other.getHostName()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateUserId() == null ? other.getUpdateUserId() == null : this.getUpdateUserId().equals(other.getUpdateUserId()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getNickName() == null) ? 0 : getNickName().hashCode());
        result = prime * result + ((getFullName() == null) ? 0 : getFullName().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getAvatar() == null) ? 0 : getAvatar().hashCode());
        result = prime * result + ((getCredit() == null) ? 0 : getCredit().hashCode());
        result = prime * result + ((getBalance() == null) ? 0 : getBalance().hashCode());
        result = prime * result + ((getCheckoutCount() == null) ? 0 : getCheckoutCount().hashCode());
        result = prime * result + ((getLastCheckoutTime() == null) ? 0 : getLastCheckoutTime().hashCode());
        result = prime * result + ((getLastLoginTime() == null) ? 0 : getLastLoginTime().hashCode());
        result = prime * result + ((getLoginCount() == null) ? 0 : getLoginCount().hashCode());
        result = prime * result + ((getLastLoginIp() == null) ? 0 : getLastLoginIp().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getLoginToken() == null) ? 0 : getLoginToken().hashCode());
        result = prime * result + ((getLoginTokenRefreshTime() == null) ? 0 : getLoginTokenRefreshTime().hashCode());
        result = prime * result + ((getTraceCodeI() == null) ? 0 : getTraceCodeI().hashCode());
        result = prime * result + ((getTraceCodeU() == null) ? 0 : getTraceCodeU().hashCode());
        result = prime * result + ((getHostName() == null) ? 0 : getHostName().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateUserId() == null) ? 0 : getUpdateUserId().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}