package org.ko.prototype.data.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ko.prototype.data.bean.domain.Dummy;
import org.ko.prototype.data.bean.domain.DummyExample;

public interface DummyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    long countByExample(DummyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByExample(DummyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insert(Dummy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insertSelective(Dummy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<Dummy> selectByExampleWithRowbounds(DummyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<Dummy> selectByExample(DummyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    Dummy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Dummy record, @Param("example") DummyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExample(@Param("record") Dummy record, @Param("example") DummyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKeySelective(Dummy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_dummy
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKey(Dummy record);
}