package org.ko.prototype.data.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ko.prototype.data.bean.domain.FileLog;
import org.ko.prototype.data.bean.domain.FileLogExample;

public interface FileLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    long countByExample(FileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByExample(FileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insert(FileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insertSelective(FileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<FileLog> selectByExampleWithRowbounds(FileLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<FileLog> selectByExample(FileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    FileLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") FileLog record, @Param("example") FileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExample(@Param("record") FileLog record, @Param("example") FileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKeySelective(FileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_file_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKey(FileLog record);
}