package org.ko.prototype.data.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ko.prototype.data.bean.domain.Keyword;
import org.ko.prototype.data.bean.domain.KeywordExample;

public interface KeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    long countByExample(KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByExample(KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insert(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insertSelective(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<Keyword> selectByExampleWithRowbounds(KeywordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<Keyword> selectByExample(KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    Keyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Keyword record, @Param("example") KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExample(@Param("record") Keyword record, @Param("example") KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKeySelective(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_keyword
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKey(Keyword record);
}