package org.ko.prototype.data.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ko.prototype.data.bean.domain.MailDate;
import org.ko.prototype.data.bean.domain.MailDateExample;

public interface MailDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    long countByExample(MailDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByExample(MailDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insert(MailDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insertSelective(MailDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<MailDate> selectByExampleWithRowbounds(MailDateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<MailDate> selectByExample(MailDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    MailDate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") MailDate record, @Param("example") MailDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExample(@Param("record") MailDate record, @Param("example") MailDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKeySelective(MailDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_mail_date
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKey(MailDate record);
}