package org.ko.prototype.data.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ko.prototype.data.bean.domain.SmsLog;
import org.ko.prototype.data.bean.domain.SmsLogExample;

public interface SmsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    long countByExample(SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByExample(SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insert(SmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insertSelective(SmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<SmsLog> selectByExampleWithBLOBsWithRowbounds(SmsLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<SmsLog> selectByExampleWithBLOBs(SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<SmsLog> selectByExampleWithRowbounds(SmsLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<SmsLog> selectByExample(SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    SmsLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") SmsLog record, @Param("example") SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SmsLog record, @Param("example") SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExample(@Param("record") SmsLog record, @Param("example") SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKeySelective(SmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_sms_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKey(SmsLog record);
}