package org.ko.prototype.data.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ko.prototype.data.bean.domain.UserActionLog;
import org.ko.prototype.data.bean.domain.UserActionLogExample;

public interface UserActionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    long countByExample(UserActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByExample(UserActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insert(UserActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int insertSelective(UserActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<UserActionLog> selectByExampleWithRowbounds(UserActionLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    List<UserActionLog> selectByExample(UserActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    UserActionLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserActionLog record, @Param("example") UserActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByExample(@Param("record") UserActionLog record, @Param("example") UserActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKeySelective(UserActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_action_log
     *
     * @mbg.generated Sat Feb 24 11:26:39 CST 2018
     */
    int updateByPrimaryKey(UserActionLog record);
}